server:
  port: 11110

spring:
  application:
    name: gabay-gateway-server
  cloud:
    gateway:
      routes:
        - id: gabay-service-provider # 路由唯一标识，通常和微服务应用名称保持一致
          uri:
          predicates:
            - Path=/** # 使用路由断言
          filters:

# eureka配置
## 用于实现动态路由

# redis配置
## 用于实现服务限流